/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 room.gltf --typescript 
Author: Katydid (https://sketchfab.com/Katydid.)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/living-roomkitchenbedroom-1f9a624a807f457488b9ae8e101d76d0
Title: Living room+kitchen+bedroom
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/model/living_room/room.gltf')
  
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.auto_12} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.auto_134} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.auto_31} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.auto_33} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.auto_32} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.auto_40} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.auto_43} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.auto_41} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.auto_47} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.auto_48} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.auto_72} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.auto_70} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.auto_80} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.auto_87} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.auto_9} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.auto} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.auto_1} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.auto_10} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.auto_101} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.auto_102} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.auto_123} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.auto_13} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.auto_105} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.auto_107} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.auto_11} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.auto_18} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.auto_19} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.auto_14} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.auto_15} />
        <mesh geometry={nodes.Object_31.geometry} material={materials.auto_16} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.auto_17} />
        <mesh geometry={nodes.Object_33.geometry} material={materials.auto_20} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.auto_21} />
        <mesh geometry={nodes.Object_35.geometry} material={materials.auto_2} />
        <mesh geometry={nodes.Object_36.geometry} material={materials.auto_23} />
        <mesh geometry={nodes.Object_37.geometry} material={materials.auto_27} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.auto_28} />
        <mesh geometry={nodes.Object_39.geometry} material={materials.auto_22} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.auto_24} />
        <mesh geometry={nodes.Object_41.geometry} material={materials.auto_25} />
        <mesh geometry={nodes.Object_42.geometry} material={materials.auto_26} />
        <mesh geometry={nodes.Object_43.geometry} material={materials.auto_29} />
        <mesh geometry={nodes.Object_44.geometry} material={materials.auto_3} />
        <mesh geometry={nodes.Object_45.geometry} material={materials.auto_30} />
        <mesh geometry={nodes.Object_46.geometry} material={materials.auto_34} />
        <mesh geometry={nodes.Object_47.geometry} material={materials.auto_39} />
        <mesh geometry={nodes.Object_48.geometry} material={materials.auto_4} />
        <mesh geometry={nodes.Object_49.geometry} material={materials.auto_35} />
        <mesh geometry={nodes.Object_50.geometry} material={materials.auto_36} />
        <mesh geometry={nodes.Object_51.geometry} material={materials.auto_37} />
        <mesh geometry={nodes.Object_52.geometry} material={materials.auto_38} />
        <mesh geometry={nodes.Object_53.geometry} material={materials.auto_44} />
        <mesh geometry={nodes.Object_54.geometry} material={materials.auto_42} />
        <mesh geometry={nodes.Object_55.geometry} material={materials.auto_51} />
        <mesh geometry={nodes.Object_56.geometry} material={materials.auto_52} />
        <mesh geometry={nodes.Object_57.geometry} material={materials.auto_45} />
        <mesh geometry={nodes.Object_58.geometry} material={materials.auto_46} />
        <mesh geometry={nodes.Object_59.geometry} material={materials.auto_49} />
        <mesh geometry={nodes.Object_60.geometry} material={materials.auto_5} />
        <mesh geometry={nodes.Object_61.geometry} material={materials.auto_50} />
        <mesh geometry={nodes.Object_62.geometry} material={materials.auto_53} />
        <mesh geometry={nodes.Object_63.geometry} material={materials.auto_54} />
        <mesh geometry={nodes.Object_64.geometry} material={materials.auto_55} />
        <mesh geometry={nodes.Object_65.geometry} material={materials.auto_56} />
        <mesh geometry={nodes.Object_66.geometry} material={materials.auto_57} />
        <mesh geometry={nodes.Object_67.geometry} material={materials.auto_58} />
        <mesh geometry={nodes.Object_68.geometry} material={materials.auto_59} />
        <mesh geometry={nodes.Object_69.geometry} material={materials.auto_6} />
        <mesh geometry={nodes.Object_70.geometry} material={materials.auto_60} />
        <mesh geometry={nodes.Object_71.geometry} material={materials.auto_61} />
        <mesh geometry={nodes.Object_72.geometry} material={materials.auto_68} />
        <mesh geometry={nodes.Object_73.geometry} material={materials.auto_69} />
        <mesh geometry={nodes.Object_74.geometry} material={materials.auto_62} />
        <mesh geometry={nodes.Object_75.geometry} material={materials.auto_63} />
        <mesh geometry={nodes.Object_76.geometry} material={materials.auto_64} />
        <mesh geometry={nodes.Object_77.geometry} material={materials.auto_65} />
        <mesh geometry={nodes.Object_78.geometry} material={materials.auto_66} />
        <mesh geometry={nodes.Object_79.geometry} material={materials.auto_67} />
        <mesh geometry={nodes.Object_80.geometry} material={materials.auto_7} />
        <mesh geometry={nodes.Object_81.geometry} material={materials.auto_71} />
        <mesh geometry={nodes.Object_82.geometry} material={materials.auto_73} />
        <mesh geometry={nodes.Object_83.geometry} material={materials.auto_74} />
        <mesh geometry={nodes.Object_84.geometry} material={materials.auto_75} />
        <mesh geometry={nodes.Object_85.geometry} material={materials.auto_76} />
        <mesh geometry={nodes.Object_86.geometry} material={materials.auto_77} />
        <mesh geometry={nodes.Object_87.geometry} material={materials.auto_78} />
        <mesh geometry={nodes.Object_88.geometry} material={materials.auto_81} />
        <mesh geometry={nodes.Object_89.geometry} material={materials.auto_79} />
        <mesh geometry={nodes.Object_90.geometry} material={materials.auto_8} />
        <mesh geometry={nodes.Object_91.geometry} material={materials.auto_82} />
        <mesh geometry={nodes.Object_92.geometry} material={materials.auto_83} />
        <mesh geometry={nodes.Object_93.geometry} material={materials.auto_84} />
        <mesh geometry={nodes.Object_94.geometry} material={materials.auto_85} />
        <mesh geometry={nodes.Object_95.geometry} material={materials.auto_86} />
        <mesh geometry={nodes.Object_96.geometry} material={materials.auto_98} />
        <mesh geometry={nodes.Object_97.geometry} material={materials.auto_97} />
      </group>
    </group>
  )
}

useGLTF.preload('/model/living_room/room.gltf')
